#!/usr/bin/env python
import sys
commitMessage = None
with open(sys.argv[1]) as commitMessageFile:
    commitMessage = commitMessageFile.read().strip()
if len(commitMessage.split("\n")[0]) > 100:
    print "Title of commit message is too long. Please add description in second row."
    sys.exit(-1)
